cmake_minimum_required(VERSION 2.8)
project( Test )
find_package( OpenCV REQUIRED )
include_directories( ${OpenCV_INCLUDE_DIRS} include/)
file(GLOB SOURCES_TOOLS "tools/*.cpp")
file(GLOB SOURCES_SRC "src/*.cpp")
add_executable( Test ${SOURCES_SRC} ${SOURCES_TOOLS} )
target_link_libraries( Test PRIVATE ${OpenCV_LIBS} )