# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/moyamryia/NJU_RM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/moyamryia/NJU_RM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moyamryia/NJU_RM/CMakeFiles /home/moyamryia/NJU_RM//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moyamryia/NJU_RM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Test

# Build rule for target.
Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Test
.PHONY : Test

# fast build rule for target.
Test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/build
.PHONY : Test/fast

src/failback.o: src/failback.cpp.o
.PHONY : src/failback.o

# target to build an object file
src/failback.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/failback.cpp.o
.PHONY : src/failback.cpp.o

src/failback.i: src/failback.cpp.i
.PHONY : src/failback.i

# target to preprocess a source file
src/failback.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/failback.cpp.i
.PHONY : src/failback.cpp.i

src/failback.s: src/failback.cpp.s
.PHONY : src/failback.s

# target to generate assembly for a file
src/failback.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/failback.cpp.s
.PHONY : src/failback.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/yoloProcess.o: src/yoloProcess.cpp.o
.PHONY : src/yoloProcess.o

# target to build an object file
src/yoloProcess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/yoloProcess.cpp.o
.PHONY : src/yoloProcess.cpp.o

src/yoloProcess.i: src/yoloProcess.cpp.i
.PHONY : src/yoloProcess.i

# target to preprocess a source file
src/yoloProcess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/yoloProcess.cpp.i
.PHONY : src/yoloProcess.cpp.i

src/yoloProcess.s: src/yoloProcess.cpp.s
.PHONY : src/yoloProcess.s

# target to generate assembly for a file
src/yoloProcess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/yoloProcess.cpp.s
.PHONY : src/yoloProcess.cpp.s

tools/tools.o: tools/tools.cpp.o
.PHONY : tools/tools.o

# target to build an object file
tools/tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/tools/tools.cpp.o
.PHONY : tools/tools.cpp.o

tools/tools.i: tools/tools.cpp.i
.PHONY : tools/tools.i

# target to preprocess a source file
tools/tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/tools/tools.cpp.i
.PHONY : tools/tools.cpp.i

tools/tools.s: tools/tools.cpp.s
.PHONY : tools/tools.s

# target to generate assembly for a file
tools/tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/tools/tools.cpp.s
.PHONY : tools/tools.cpp.s

tools/videoReader.o: tools/videoReader.cpp.o
.PHONY : tools/videoReader.o

# target to build an object file
tools/videoReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/tools/videoReader.cpp.o
.PHONY : tools/videoReader.cpp.o

tools/videoReader.i: tools/videoReader.cpp.i
.PHONY : tools/videoReader.i

# target to preprocess a source file
tools/videoReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/tools/videoReader.cpp.i
.PHONY : tools/videoReader.cpp.i

tools/videoReader.s: tools/videoReader.cpp.s
.PHONY : tools/videoReader.s

# target to generate assembly for a file
tools/videoReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/tools/videoReader.cpp.s
.PHONY : tools/videoReader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Test"
	@echo "... src/failback.o"
	@echo "... src/failback.i"
	@echo "... src/failback.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/yoloProcess.o"
	@echo "... src/yoloProcess.i"
	@echo "... src/yoloProcess.s"
	@echo "... tools/tools.o"
	@echo "... tools/tools.i"
	@echo "... tools/tools.s"
	@echo "... tools/videoReader.o"
	@echo "... tools/videoReader.i"
	@echo "... tools/videoReader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

